import React from 'react';
import { StyleSheet, Text, View, FlatList } from 'react-native';
import ListItem from './ListItem.js';


export default function Following() {
  const renderItem = ({ item }) => (
    <ListItem username={item.username} />
  )
  return (
    <View>
      <FlatList data={list} renderItem={renderItem} keyExtractor={item => item.id} />
    </View>
  );
}

const list = [
  { id: 0, username: 'Goku' },
  { id: 1, username: 'Gohan' },
  { id: 2, username: 'Goten' },
  { id: 3, username: 'Vegeta' },
  { id: 4, username: 'Trunks' },
  { id: 5, username: 'Broly' },
  { id: 6, username: 'Piccolo' },
  { id: 7, username: 'Frieza' },
  { id: 8, username: 'Bulma' },
  { id: 9, username: 'Bardock' },
  { id: 10, username: 'Goku' },
  { id: 11, username: 'Gohan' },
  { id: 12, username: 'Goten' },
  { id: 13, username: 'Vegeta' },
  { id: 14, username: 'Trunks' },
  { id: 15, username: 'Broly' },
  { id: 16, username: 'Piccolo' },
  { id: 17, username: 'Frieza' },
  { id: 18, username: 'Bulma' },
  { id: 19, username: 'Bardock' },
  { id: 20, username: 'Goku' },
  { id: 21, username: 'Gohan' },
  { id: 22, username: 'Goten' },
  { id: 23, username: 'Vegeta' },
  { id: 24, username: 'Trunks' },
  { id: 25, username: 'Broly' },
  { id: 26, username: 'Piccolo' },
  { id: 27, username: 'Frieza' },
  { id: 28, username: 'Bulma' },
  { id: 29, username: 'Bardock' },
  { id: 30, username: 'Goku' },
  { id: 31, username: 'Gohan' },
  { id: 32, username: 'Goten' },
  { id: 33, username: 'Vegeta' },
  { id: 34, username: 'Trunks' },
  { id: 35, username: 'Broly' },
  { id: 36, username: 'Piccolo' },
  { id: 37, username: 'Frieza' },
  { id: 38, username: 'Bulma' },
  { id: 39, username: 'Bardock' },
  { id: 40, username: 'Goku' },
  { id: 41, username: 'Gohan' },
  { id: 42, username: 'Goten' },
  { id: 43, username: 'Vegeta' },
  { id: 44, username: 'Trunks' },
  { id: 45, username: 'Broly' },
  { id: 46, username: 'Piccolo' },
  { id: 47, username: 'Frieza' },
  { id: 48, username: 'Bulma' },
  { id: 49, username: 'Bardock' },
  { id: 50, username: 'Goku' },
  { id: 51, username: 'Gohan' },
  { id: 52, username: 'Goten' },
  { id: 53, username: 'Vegeta' },
  { id: 54, username: 'Trunks' },
  { id: 55, username: 'Broly' },
  { id: 56, username: 'Piccolo' },
  { id: 57, username: 'Frieza' },
  { id: 58, username: 'Bulma' },
  { id: 59, username: 'Bardock' },
  { id: 60, username: 'Goku' },
  { id: 61, username: 'Gohan' },
  { id: 62, username: 'Goten' },
  { id: 63, username: 'Vegeta' },
  { id: 64, username: 'Trunks' },
  { id: 65, username: 'Broly' },
  { id: 66, username: 'Piccolo' },
  { id: 67, username: 'Frieza' },
  { id: 68, username: 'Bulma' },
  { id: 69, username: 'Bardock' },
  { id: 70, username: 'Goku' },
  { id: 71, username: 'Gohan' },
  { id: 72, username: 'Goten' },
  { id: 73, username: 'Vegeta' },
  { id: 74, username: 'Trunks' },
  { id: 75, username: 'Broly' },
  { id: 76, username: 'Piccolo' },
  { id: 77, username: 'Frieza' },
  { id: 78, username: 'Bulma' },
  { id: 79, username: 'Bardock' },
  { id: 80, username: 'Goku' },
  { id: 81, username: 'Gohan' },
  { id: 82, username: 'Goten' },
  { id: 83, username: 'Vegeta' },
  { id: 84, username: 'Trunks' },
  { id: 85, username: 'Broly' },
  { id: 86, username: 'Piccolo' },
  { id: 87, username: 'Frieza' },
  { id: 88, username: 'Bulma' },
  { id: 89, username: 'Bardock' },
  { id: 90, username: 'Goku' },
  { id: 91, username: 'Gohan' },
  { id: 92, username: 'Goten' },
  { id: 93, username: 'Vegeta' },
  { id: 94, username: 'Trunks' },
  { id: 95, username: 'Broly' },
  { id: 96, username: 'Piccolo' },
  { id: 97, username: 'Frieza' },
  { id: 98, username: 'Bulma' },
  { id: 99, username: 'Bardock' }
];